### ISSUE TITLE
Peer Review by Amanda Eriksson Skog

### ISSUE THREAD

**Issue by amaerisk** [teokem/project-work-2020-yuliiahrabar#1]
Dear Yuliia,

I think that you notebook is very well written with a nice introduction and also a clear guide how to run the notebook, well done! I found that you have included all the required parts from the notebook requirement guide. The only comment I have where you could make an improvement is the "Plots of all simulations" at the end of your notebook where a performance warning is given. This is also the same below the headline "Asymmetric fission case". Maybe you are able to rewrite the input to get rid of the warnings? Other than that I think the notebook is very nice.

Best,

Amanda Eriksson Skog

**Comment by yuliiahrabar** [comment]
Dear Amanda, 

Thank you for your peer review. I resolved the issue with the performance warning by sorting index of my DataFrame. 

Best regards,
Yuliia Hrabar
