### ISSUE TITLE
Peer Review - Daniel Sarabi

### ISSUE THREAD

**Issue by danielsarabi** [teokem/project-work-2020-yuliiahrabar#2]
- [x] **Documentation:**

- [x] title and abstract of the project (max 300 words)

- [x]  includes instructions on how to run the notebook

- [x] includes the required packages in an environment.yml file

- [x]  includes a brief explanation of the reason each package/library was used

- [x]  includes rich documentation using Markdown (equations, tables, links, images or videos)

- [x]  is reproducible, i.e., someone else should be able to redo the steps

- [ ] **Input/Output:**

- [x] uses pandas to read large data sets or numpy to load data from text files
 
- [ ] uses pandas to save to disk the processed or generated data - _Im not sure if the data was saved to disk. Maybe you can save the variable asymm225 as data frame using pandas._ 

- [x] **Scientific computing/data processing:**
 
- [x] performs numerical operations (numpy, scipy, pandas) or manipulates, groups, and aggregates a data set (pandas)

- [x] **Data visualization:**

- [x]  includes at least one composite plot (inset or multiple panels)

- [x]  produces publication ready quality figures 

- [x] the figures are 89 mm wide (single column) or 183 mm wide (double column)

- [x] the axes are labeled

- [x] the font sizes are sufficiently large

- [x] the figures are saved as rasterized images (300 dpi) or vector art

- [x]  **Version control, sharing, and archiving:**
 is archived in a repository with a digital object identifier (DOI)

Very nice notebook, it looks great.  well done Yuliia!

**Comment by yuliiahrabar** [comment]
Dear Daniel Sarabi, 

Thank you for your peer review. 

Generated data is saved to disk in the Jupyter Notebook  GEANT4_Read_ROOT_files.ipynb, which is a part of my project as well. The issue has been resolved. 

Best regards,
Yuliia Hrabar
